// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyBodyMetrics,
    foodEntries,
    mealTemplates,
    dailyChecks,
    foodEntriesEatenAt,
  ];
  late final Shape0 dailyBodyMetrics = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_body_metrics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foodEntries = Shape1(
    source: i0.VersionedTable(
      entityName: 'food_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 mealTemplates = Shape2(
    source: i0.VersionedTable(
      entityName: 'meal_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_19,
        _column_20,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 dailyChecks = Shape3(
    source: i0.VersionedTable(
      entityName: 'daily_checks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day, item)'],
      columns: [_column_0, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index foodEntriesEatenAt = i1.Index(
    'food_entries_eaten_at',
    'CREATE INDEX food_entries_eaten_at ON food_entries (eaten_at)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get measuredAt =>
      columnsByName['measured_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get bodyFatPercent =>
      columnsByName['body_fat_percent']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get leanMassKg =>
      columnsByName['lean_mass_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get leanMassEstimated =>
      columnsByName['lean_mass_estimated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'measured_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_2(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'weight_kg',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_3(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'body_fat_percent',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_4(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lean_mass_kg',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'lean_mass_estimated',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (lean_mass_estimated IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'synced_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get eatenAt =>
      columnsByName['eaten_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get meal =>
      columnsByName['meal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get servings =>
      columnsByName['servings']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get kcal =>
      columnsByName['kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get proteinG =>
      columnsByName['protein_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbsG =>
      columnsByName['carbs_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fatG =>
      columnsByName['fat_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get templateId =>
      columnsByName['template_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'eaten_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'servings',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 1.0',
      defaultValue: const i1.CustomExpression('1.0'),
    );
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'kcal',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carbs_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fat_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'template_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'created_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meal =>
      columnsByName['meal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get defaultServings =>
      columnsByName['default_servings']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get kcal =>
      columnsByName['kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get proteinG =>
      columnsByName['protein_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbsG =>
      columnsByName['carbs_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fatG =>
      columnsByName['fat_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get pinned =>
      columnsByName['pinned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archived =>
      columnsByName['archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get useCount =>
      columnsByName['use_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUsedAt =>
      columnsByName['last_used_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'default_servings',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 1.0',
      defaultValue: const i1.CustomExpression('1.0'),
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pinned',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (pinned IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'use_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_used_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get item =>
      columnsByName['item']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get checkedAt =>
      columnsByName['checked_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'checked_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyBodyMetrics,
    foodEntries,
    mealTemplates,
    dailyChecks,
    phases,
    foodEntriesEatenAt,
  ];
  late final Shape0 dailyBodyMetrics = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_body_metrics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foodEntries = Shape1(
    source: i0.VersionedTable(
      entityName: 'food_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 mealTemplates = Shape2(
    source: i0.VersionedTable(
      entityName: 'meal_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_19,
        _column_20,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 dailyChecks = Shape3(
    source: i0.VersionedTable(
      entityName: 'daily_checks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day, item)'],
      columns: [_column_0, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 phases = Shape4(
    source: i0.VersionedTable(
      entityName: 'phases',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index foodEntriesEatenAt = i1.Index(
    'food_entries_eaten_at',
    'CREATE INDEX food_entries_eaten_at ON food_entries (eaten_at)',
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startDay =>
      columnsByName['start_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endDay =>
      columnsByName['end_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hypothesis =>
      columnsByName['hypothesis']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get targetKcal =>
      columnsByName['target_kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get targetProteinG =>
      columnsByName['target_protein_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get creatine =>
      columnsByName['creatine']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get conclusion =>
      columnsByName['conclusion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'start_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'end_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hypothesis',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_30(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'target_kcal',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'target_protein_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'creatine',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (creatine IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'conclusion',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyBodyMetrics,
    foodEntries,
    mealTemplates,
    dailyChecks,
    phases,
    profiles,
    foodEntriesEatenAt,
  ];
  late final Shape0 dailyBodyMetrics = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_body_metrics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foodEntries = Shape1(
    source: i0.VersionedTable(
      entityName: 'food_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 mealTemplates = Shape2(
    source: i0.VersionedTable(
      entityName: 'meal_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_19,
        _column_20,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 dailyChecks = Shape3(
    source: i0.VersionedTable(
      entityName: 'daily_checks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day, item)'],
      columns: [_column_0, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 phases = Shape4(
    source: i0.VersionedTable(
      entityName: 'phases',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 profiles = Shape5(
    source: i0.VersionedTable(
      entityName: 'profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_2,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index foodEntriesEatenAt = i1.Index(
    'food_entries_eaten_at',
    'CREATE INDEX food_entries_eaten_at ON food_entries (eaten_at)',
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get birthYear =>
      columnsByName['birth_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get heightCm =>
      columnsByName['height_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get activity =>
      columnsByName['activity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get tdeeKcal =>
      columnsByName['tdee_kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sex',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'birth_year',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'height_cm',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'activity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_39(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tdee_kcal',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyBodyMetrics,
    foodEntries,
    mealTemplates,
    dailyChecks,
    phases,
    profiles,
    dailyActivity,
    foodEntriesEatenAt,
  ];
  late final Shape0 dailyBodyMetrics = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_body_metrics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foodEntries = Shape1(
    source: i0.VersionedTable(
      entityName: 'food_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 mealTemplates = Shape2(
    source: i0.VersionedTable(
      entityName: 'meal_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_19,
        _column_20,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 dailyChecks = Shape3(
    source: i0.VersionedTable(
      entityName: 'daily_checks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day, item)'],
      columns: [_column_0, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 phases = Shape4(
    source: i0.VersionedTable(
      entityName: 'phases',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 profiles = Shape6(
    source: i0.VersionedTable(
      entityName: 'profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_2,
        _column_39,
        _column_41,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 dailyActivity = Shape7(
    source: i0.VersionedTable(
      entityName: 'daily_activity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [_column_0, _column_42, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index foodEntriesEatenAt = i1.Index(
    'food_entries_eaten_at',
    'CREATE INDEX food_entries_eaten_at ON food_entries (eaten_at)',
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get birthYear =>
      columnsByName['birth_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get heightCm =>
      columnsByName['height_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get activity =>
      columnsByName['activity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get tdeeKcal =>
      columnsByName['tdee_kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get energyMode =>
      columnsByName['energy_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'energy_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'watch\'',
      defaultValue: const i1.CustomExpression('\'watch\''),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get activeKcal =>
      columnsByName['active_kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_42(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'active_kcal',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyBodyMetrics,
    foodEntries,
    mealTemplates,
    dailyChecks,
    phases,
    profiles,
    dailyActivity,
    extraBurns,
    foodEntriesEatenAt,
  ];
  late final Shape0 dailyBodyMetrics = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_body_metrics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foodEntries = Shape1(
    source: i0.VersionedTable(
      entityName: 'food_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 mealTemplates = Shape2(
    source: i0.VersionedTable(
      entityName: 'meal_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_19,
        _column_20,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 dailyChecks = Shape3(
    source: i0.VersionedTable(
      entityName: 'daily_checks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day, item)'],
      columns: [_column_0, _column_25, _column_26],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 phases = Shape4(
    source: i0.VersionedTable(
      entityName: 'phases',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_10,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 profiles = Shape6(
    source: i0.VersionedTable(
      entityName: 'profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_2,
        _column_39,
        _column_41,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 dailyActivity = Shape7(
    source: i0.VersionedTable(
      entityName: 'daily_activity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [_column_0, _column_42, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 extraBurns = Shape8(
    source: i0.VersionedTable(
      entityName: 'extra_burns',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_7, _column_0, _column_43, _column_16, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index foodEntriesEatenAt = i1.Index(
    'food_entries_eaten_at',
    'CREATE INDEX food_entries_eaten_at ON food_entries (eaten_at)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get kcal =>
      columnsByName['kcal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_43(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'kcal',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
  ),
);
